# name: Deploy to VPS

# on:
#   push:
#     branches:
#       - main  # Déclenchement du déploiement lors du push sur la branche "main"

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Connect to VPS via SSH
#       uses: appleboy/ssh-action@v0.1.3
#       with:
#         host: ${{ secrets.VPS_HOST }}  # Adresse IP de ton VPS
#         username: ${{ secrets.VPS_USER }}  # Utilisateur SSH du VPS
#         key: ${{ secrets.VPS_SSH_KEY }}  # Clé SSH privée
#         port: 22  # Le port SSH par défaut est 22
#         script: |
#           echo "Connexion réussie au VPS"
name: Deploy Express App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image to Docker Hub
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-express-app .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-express-app

    - name: Deploy to VPS via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/my-express-app
          docker stop express-app || true
          docker rm express-app || true
          docker run -d -p 3000:3000 --name express-app ${{ secrets.DOCKER_USERNAME }}/my-express-app
