name: Deploy to VPS

on:
  push:
    branches:
      - main  # Déclenchement du déploiement lors du push sur la branche "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Connect to VPS via SSH
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: ${{ secrets.VPS_HOST }}  # Adresse IP de ton VPS
        username: ${{ secrets.VPS_USER }}  # Utilisateur SSH du VPS
        key: ${{ secrets.VPS_SSH_KEY }}  # Clé SSH privée
        port: 22  # Le port SSH par défaut est 22
        script: |
          echo "Connexion réussie au VPS"
